#! /bin/sh

# xmodmap .xmodmap-sid & # remove this 

# bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 4
bspc monitor DP-4 -d 3
bspc monitor DP-0 -d 2
# bspc monitor -d 1

bspc config border_width         3
bspc config borderless_monocle   false

bspc config window_gap            10
bspc config split_ratio           0.50
# bspc config gapless_monocle       true # this puts a space between polybar and the windows
bspc config focus_follows_pointer true

bspc config top_padding 32

bspc config focused_border_color "#98971a"
# bspc config normal_border_color "#353b45"

# autostart up applications 
picom & 
feh --bg-fill ~/.wallpaper/2.png &
xrdb merge ~/.Xresources &
~/.config/polybar/launch.sh &
sxhkd 
